### ISSUE TITLE
TODO lists

### ISSUE THREAD

**Issue by Jabawack** [Jabawack/jabawack.github.io#1]
- [x] Initial release
- [x] Update the resume and upload to github
- [x] Create "about" page
- [ ] Create "WebReactor" page
- [x] Create "Tapyn" page
- [ ] Create "Workato" page
- [ ] Create "Kurbo" page
- [ ] Update "Passion Projects"
- [x] Add .gitignore
- [x] Add README.md
- [ ] Add google analytics
- [ ] connect DB (https://firebase.google.com maybe?)
- [x] Start a Wiki page
